services:
  laravel-app:
    image: carvajalvalverde
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    working_dir:
      /var/www/html/carvajalvalverde
    volumes:
      - .:/var/www/html/carvajalvalverde
